### ISSUE TITLE
Support for dataclasses

### ISSUE THREAD

**Issue by nielstron** [vemel/handsdown#30]
**Is your feature request related to a problem? Please describe.**
I would like to build the documentation for my project with this, but it is mainly consisting of dataclasses.
I use them precisely because they implicitly build initializers from attributes with type annotation.

**Describe the solution you'd like**
The following code

```
@dataclass()
class A:
    b: int
    # This comment should also appear in the docs
    c: str
```

Should have in its documentation the fact that A has the attributes b and c with the annotated type.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by vemel** [comment]
Thank you fo the feature request! I will definitely add it.

**Comment by vemel** [comment]
There was no support for annotated assignments. Added in `2.1.0`. Please update and let me know if it works as expected for you.
