### ISSUE TITLE
Documentation of private and protected methods

### ISSUE THREAD

**Issue by dvdblk** [vemel/handsdown#31]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a documentation for a bunch of python code (not a pypi package) and I would like to see the documentation for protected and private methods too. I'm wondering if this is something you would like to support in the future? 

**Describe the solution you'd like**
Private and protected method documentation should be visible in the generated docs.

**Describe alternatives you've considered**
Changing methods to public.

**Additional context**
None :)

**Comment by vemel** [comment]
I am going to add support for private and protected methods. I will add a new CLI flag for this.

**Comment by yurii-vasylkiv** [comment]
any updates?

**Comment by vemel** [comment]
@yurii-vasylkiv yes. Already pushed changes to `main`. Expect a new release today or tomorrow.

**Comment by vemel** [comment]
Private and protected methods are included to docs starting from version `2.1.0`. Please update and let me know if it works as expected.

**Comment by yurii-vasylkiv** [comment]
> Documented private and protected methods are added to docs starting from version `2.1.0`. Please update and let me know if it works as expected.

Fantastic!!! Thank you so much !!! Your utility is saving me tons of time!!!
