### ISSUE TITLE
Error when pulling Docker image

### ISSUE THREAD

**Issue by conery** [vemel/handsdown#32]
**Describe the bug**
Docker fails with "no basic auth credentials" when pulling the handsdown image

**To Reproduce**
I copied the shell command from the README:
```
$ docker pull docker.pkg.github.com/vemel/handsdown/handsdown:latest
Error response from daemon: Head "https://docker.pkg.github.com/v2/vemel/handsdown/handsdown/manifests/latest": no basic auth credentials
```

**Desktop (please complete the following information):**
 - OS:  macOS
 - Version 14.0 ("Sonoma")
 - Host:  iMac with Core i7 processor
 - Docker version 24.0.6

**Comment by vemel** [comment]
Thank you! I will take a look

**Comment by vemel** [comment]
Obviously, GitHub changed links for Docker images. Use `docker pull ghcr.io/vemel/handsdown/handsdown` instead. I updated the docs as well. Let me know if this helps.

```bash
docker pull ghcr.io/vemel/handsdown/handsdown:latest
docker tag ghcr.io/vemel/handsdown/handsdown:latest handsdown
```

**Comment by conery** [comment]
Works great -- thanks!  (and sorry for the slow response, got sidetracked there...)

**Comment by conery** [comment]
Image now at Docker.
