### ISSUE TITLE
Module docstrings are not included in the documentation

### ISSUE THREAD

**Issue by fhoussiau** [vemel/handsdown#36]
**Describe the bug**
The text included in the `"""docstring"""` at the top of a module is not "rendered" in the Markdown. For instance, the [main example](https://github.com/vemel/handsdown/blob/main/examples/main_example.py) starts as:
```python
"""
This is a module docstring. It will appear in documentation.

## Notes

You can use Markdown here to make it nicer. Also, in any docstring you
can put a global object import string in backticks, like `other_module.OtherClass`,
and it will be transformed to a link.
"""
```

but [the output](https://github.com/vemel/handsdown/blob/docs/docsmd/examples/main_example.md) ignores this text:

```markdown
# Main Example

[Handsdown API Index](../README.md#handsdown-api-index) / [Examples](./index.md#examples) / Main Example

> Auto-generated documentation for [examples.main_example](https://github.com/vemel/handsdown/blob/main/examples/main_example.py) module.
```

This doesn't seem to be the intended behaviour, given the example.

**To Reproduce**
I've had this issue with every file. See all examples.

**Expected behavior**
The module docstring included.

**Desktop (please complete the following information):**
 - OS: Linux
 - Ubuntu 24.04

**Comment by vemel** [comment]
Hello. THank you for the report. THis is definitely a bug, I will check.

**Comment by fhoussiau** [comment]
Hello, many thanks for your answer! Have you had time to look into the issue?

**Comment by jasongill** [comment]
hey @vemel can you merge #38 to fix this? Thank you!
