### ISSUE TITLE
Backslashes inserted in windows paths 

### ISSUE THREAD

**Issue by FredHappyface** [vemel/handsdown#9]
**Describe the bug**

File paths include backslashes when running this in powershell on a windows 10 machine causing things to break when git pushed

for example:

```md
# Test Modules

> Auto-generated documentation modules index.

Full list of [Test](README.md#test-index) project modules.

- [Test Index](README.md#test-index)
- [Ansitoimg](ansitoimg\index.md#ansitoimg)
    - [Ansirep](ansitoimg\ansirep.md#ansirep)
    - [Render](ansitoimg\render.md#render)
    - [Utils](ansitoimg\utils.md#utils)
```

**To Reproduce**

1. clone https://github.com/FredHappyface/test (though any project will demonstrate this)
2. install and run `handsdown` on windows 10 in powershell
3. see the snippet for an example of the output 

```md
# Test Modules

> Auto-generated documentation modules index.

Full list of [Test](README.md#test-index) project modules.

- [Test Index](README.md#test-index)
- [Ansitoimg](ansitoimg\index.md#ansitoimg)
    - [Ansirep](ansitoimg\ansirep.md#ansirep)
    - [Render](ansitoimg\render.md#render)
    - [Utils](ansitoimg\utils.md#utils)
```

**Expected behavior**
Forward slashes to be inserted as on linux/ wsl 

```md
# Test Modules

> Auto-generated documentation modules index.

Full list of [Test](README.md#test-index) project modules.

- [Test Index](README.md#test-index)
- [Ansitoimg](ansitoimg/index.md#ansitoimg)
    - [Ansirep](ansitoimg/ansirep.md#ansirep)
    - [Render](ansitoimg/render.md#render)
    - [Utils](ansitoimg/utils.md#utils)
```
**Screenshots**

Following a current link leads to a 'page not found'

![image](https://user-images.githubusercontent.com/41634689/84008975-7bfc9600-a96a-11ea-9a8e-1d2f883c5cfc.png)

due to the backslash 
https://github.com/FredHappyface/test/blob/master/DOCS/ansitoimg%5Cindex.md#ansitoimg

**Desktop (please complete the following information):**

Windows 10 Home 1909

**Additional context**

Thanks for an awesome project and your time! 😄

**Comment by FredHappyface** [comment]
Just to add to this, I have located the bug 

https://github.com/vemel/handsdown/blob/master/handsdown/md_document.py
def render_doc_link(self, title, anchor="", target_path=None):


I have also implemented a fix on my local machine.

Changed
```python
if anchor:
   link = "#{}".format(anchor)
if target_path and target_path != self._path:
   link_path = self._path_finder.relative(target_path)
   link = "{}{}".format(link_path, link)

return self.render_link(title, link)
```

To
```python
if anchor:
   link = "#{}".format(anchor)
if target_path and target_path != self._path:
   link_path = self._path_finder.relative(target_path)
   # need to replace \\ with /
   link_path = str(link_path).replace("\\", "/")
   link = "{}{}".format(link_path, link)

return self.render_link(title, link)
```


Would you accept a pull request for this?

Thanks again

**Comment by pavel-rezabek** [comment]
This can be also resolved by changing the way link_path is formatted:
```
link = "{}{}".format(link_path, link)
```
to
```
link = "{}{}".format(link_path.as_posix(), link)
```
